//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd5tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharacterID { get; set; }
        public string AspNetUserID { get; set; }
        public int RaceID { get; set; }
        public string Name { get; set; }
        public int Str { get; set; }
        public int Dex { get; set; }
        public int Con { get; set; }
        public int Int { get; set; }
        public int Wis { get; set; }
        public int Cha { get; set; }
        public int ProficiencyBonus { get; set; }
        public int StrengthSavingThrow { get; set; }
        public int DexteritySavingThrow { get; set; }
        public int ConstitutionSavingThrow { get; set; }
        public int IntelligenceSavingThrow { get; set; }
        public int WisdomSavingThrow { get; set; }
        public int CharismaSavingThrow { get; set; }
        public int Acrobatics { get; set; }
        public int AnimalHandling { get; set; }
        public int Arcana { get; set; }
        public int Athletics { get; set; }
        public int Deception { get; set; }
        public int History { get; set; }
        public int Insight { get; set; }
        public int Intimidation { get; set; }
        public int Investigation { get; set; }
        public int Medicine { get; set; }
        public int Nature { get; set; }
        public int Perception { get; set; }
        public int Performance { get; set; }
        public int Persuasion { get; set; }
        public int Religion { get; set; }
        public int SleightOfHand { get; set; }
        public int Stealth { get; set; }
        public int Survival { get; set; }
        public int ArmorClass { get; set; }
        public int Initiative { get; set; }
        public int Speed { get; set; }
        public int HitPointMaximum { get; set; }
        public int CurrentHitPoints { get; set; }
        public int TemporaryHitpoints { get; set; }
        public string HitDice { get; set; }
        public string PersonalityTraits { get; set; }
        public string Ideals { get; set; }
        public string Bonds { get; set; }
        public string Flaws { get; set; }
        public string Proficiencies { get; set; }
        public string FeaturesAndTraits { get; set; }
        public int Age { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Eyes { get; set; }
        public string Skin { get; set; }
        public string Hair { get; set; }
        public string AlliesAndOrganizations { get; set; }
        public string BackStory { get; set; }
        public string Treasure { get; set; }
        public int Copper { get; set; }
        public int Silver { get; set; }
        public int Electrum { get; set; }
        public int Gold { get; set; }
        public int Platinum { get; set; }
        public string Class { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Race Race { get; set; }
    }
}
