//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd5tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.SpellReviews = new HashSet<SpellReview>();
        }
    
        public int ClassID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SpellReview> SpellReviews { get; set; }
    }
}
