//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd5tools.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dnd5toolsDbContext : DbContext
    {
        public dnd5toolsDbContext()
            : base("name=dnd5toolsDbContext")
        {
    
        this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Spell> Spells { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<SpellReview> SpellReviews { get; set; }
        public virtual DbSet<SpellWithRating> SpellWithRatings { get; set; }
        public virtual DbSet<ReviewVote> ReviewVotes { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
    }
}
