//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd5tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.SpellReviews = new HashSet<SpellReview>();
        }
    
        public int ReviewID { get; set; }
        public string UserID { get; set; }
        public string Headline { get; set; }
        public string Comment { get; set; }
        public int Rating { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<SpellReview> SpellReviews { get; set; }
    }
}
