//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd5tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpellReview
    {
        public int SpellReviewID { get; set; }
        public string UserID { get; set; }
        public int SpellID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public double Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Spell Spell { get; set; }
    }
}
