//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnd5tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        public Spell()
        {
            this.SpellReviews = new HashSet<SpellReview>();
        }
    
        public int SpellID { get; set; }
        public string School { get; set; }
        public string CastingTime { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Level { get; set; }
        public bool IsRitual { get; set; }
        public bool IsConcentration { get; set; }
        public string Components { get; set; }
        public string ComponentsFlavorText { get; set; }
        public bool HasComponentCost { get; set; }
        public string Source { get; set; }
        public int Page { get; set; }
    
        public virtual ICollection<SpellReview> SpellReviews { get; set; }
    }
}
